### ISSUE TITLE
changing script settings does not work properly

### ISSUE THREAD

**Issue by qwertz44** [Opmantek/open-audit#18]
Hi,
i´ve edited the settings of the audit_windows script in open-audits gui and downloaded the script. But some settings are set, some not. For example as you can see in the attached screenshot the option for using dns is set in the gui but not in the downloaded script file.

![Capture](https://github.com/user-attachments/assets/4ab57e95-1d60-444e-8f8c-6b1ca3998d6a)

**Comment by mark-unwin** [comment]
I am assuming this was closed because you found where the application injects the settings into the script (further down at about lines 136 onwards? I just tested and it is working as expected.
